// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZhHmDDDI-CBiH9E3QgH4MhnisLnWevOg',
    appId: '1:611801854065:web:fd057aa161e89975ddebd0',
    messagingSenderId: '611801854065',
    projectId: 'reddit-clone-ea1e6',
    authDomain: 'reddit-clone-ea1e6.firebaseapp.com',
    storageBucket: 'reddit-clone-ea1e6.appspot.com',
    measurementId: 'G-PD4DTEEFH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyConl4iE4g4w2N9ZXKVe-3gEPmKyeq8RCE',
    appId: '1:611801854065:android:d73ae74a0fa36588ddebd0',
    messagingSenderId: '611801854065',
    projectId: 'reddit-clone-ea1e6',
    storageBucket: 'reddit-clone-ea1e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7EsFrqXRzxLHRUj8Itnw83bwa1BorKSg',
    appId: '1:611801854065:ios:cc8bd851f148e267ddebd0',
    messagingSenderId: '611801854065',
    projectId: 'reddit-clone-ea1e6',
    storageBucket: 'reddit-clone-ea1e6.appspot.com',
    iosClientId: '611801854065-aovl880te19i8ourjp6n6uirp5qb5q70.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterreditclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7EsFrqXRzxLHRUj8Itnw83bwa1BorKSg',
    appId: '1:611801854065:ios:cc8bd851f148e267ddebd0',
    messagingSenderId: '611801854065',
    projectId: 'reddit-clone-ea1e6',
    storageBucket: 'reddit-clone-ea1e6.appspot.com',
    iosClientId: '611801854065-aovl880te19i8ourjp6n6uirp5qb5q70.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterreditclone',
  );
}
